### ISSUE TITLE
Custom Hotbar is on top of tool tips from core hotbar

### ISSUE THREAD

**Issue by Sparkasaurusmex** [Norc/foundry-custom-hotbar#61]
When I hover over the core hotbar the tool tips appear behind the custom hotbar.

**Comment by Norc** [comment]
Can you confirm that you are on 2.0.4? My 2.0.3 had this issue but I thought i fixed it in 2.0.4.

**Comment by Sparkasaurusmex** [comment]
Ah!  I was somehow on the older version using the Update All function under
modules.  It automatically updated when I clicked the update box for Custom
Hotbars.

**Comment by Norc** [comment]
Perfect! I think you just happened to update exactly in the 20 minutes that I had be incorrect version out there, glad it's resolved thanks.

**Comment by Sparkasaurusmex** [comment]
Thank for the awesome module!

**Comment by Sparkasaurusmex** [comment]
Sorry, but this still seems to be the case after updating to 2.04!

**Comment by Norc** [comment]
Sorry I only got this email notification now. There still seems to be an issue with 2.0.4 that i thought I fixed. I'll get this sorted in the next few hours, sorry about the inconvenience.

**Comment by Sparkasaurusmex** [comment]
I actually moved your hotbar to the right of the core one.  It solved the
problem and I like it better there anyway.

**Comment by Norc** [comment]
Nice! Yeah, good thinking and I'm glad to hear it.
v2.0.5 has the fix for the issue finally anyway. I need to update gmail so these "new email" notifications don't get shuffled under the "forums" tab... I could've fixed this in about 15 minutes if I had known it was still an issue. Sigh.
Anyway, thanks very much for the report, and let me know if there's anything I can do to make the module better for you.
