### ISSUE TITLE
No longer able to right click delete macros from  the main hotbar.

### ISSUE THREAD

**Issue by Ssezra** [Norc/foundry-custom-hotbar#62]
The current custom hotbar module is preventing the deletion of macros on the main hotbar.  Even if minimized the custom hotbar appears to be blocking the option to right click a macro and delete from the main hotbar. (it also partially blocks the remove option; but edit it selectable) A user can only highlight a macro in the main hotbar and hit the delete key; or select the macro directory and delete. If the module is disabled, macros can be deleted by right clicking and selecting delete.

**Comment by Norc** [comment]
Sorry I only got this email notification now. There still seems to be an issue with 2.0.4 that i thought I fixed. I'll get this sorted in the next few hours, sorry about the inconvenience.

**Comment by Norc** [comment]
v2.0.5 has the fix for the issue that I thought i deployed in v2.0.4. I'm terribly sorry about that and about the delay. I need to update gmail so these "new issue" notifications don't get shuffled under the "forums" tab... I could've fixed this in about 15 minutes if I had known it was still an issue. Sigh.

Anyway, thanks very much for the report, and let me know if there's anything I can do to make the module better for you. If the issue is not resolved, please let me know on discord (Norc#5108) or update and reopen this ticket.
