### ISSUE TITLE
Feature Request: Option to disable Custom Hotbar for players

### ISSUE THREAD

**Issue by Norc** [Norc/foundry-custom-hotbar#72]
Originally requested by Unsoluble

**Comment by Shuggaloaf** [comment]
New to Github so sorry if this isn't the appropriate place. Just want to 2nd (3rd?) this request. 
Due mainly to this issue (& players small screens) I'm actually having to uninstall. 
Thought stacking the hotbars would be a solution but another issue with right-click menu often displaying behind main hotbar, it was not. 
Will be monitoring closely as this is a very helpful and excellent mod otherwise (and I already miss it!)

**Comment by Norc** [comment]
Added the ability to disable the display of the Custom Hotbar for players. Under the hood, it's still present, but it doesn't render at all.

While I was at it, I also added the same ability to disable the core Foundry Hotbar...
