### ISSUE TITLE
ChatMessage.create in macro spawns an extra chat message with shift+#

### ISSUE THREAD

**Issue by jacobjorvang** [Norc/foundry-custom-hotbar#82]
Ex:

let chatData = {
  user: game.user._id,
  content: "test",
  whisper: [game.user._id],
};
ChatMessage.create(chatData, {});

**Comment by buttonpushertv** [comment]
I came over to submit a similar issue. It appears, to me, that is is actually firing the macro on a given Custom Hotbar twice for a single keypress. Maybe it's polling the keyboard input too fast and that's registering as multiple invocations of the macro under a given hotbar slot?

**Comment by jacobjorvang** [comment]
Yeah, since I submitted this I realised that it actually runs every macro twice simultaneously if using the hotkeys, but one if using a mouse press.

**Comment by Norc** [comment]
Are you folks using Better Rolls and/or Firefox by any chance?

**Comment by jacobjorvang** [comment]
No, neither of those. Using Chrome.

**Comment by buttonpushertv** [comment]
Chrome here too (Norc we chatted earlier on Discord about CHB not working on a RPi server. Re-install did the trick.)

I had Better Rolls enabled for a bit but then have since disabled it. It's still running the macros twice when invoked by key press. For me, mouse clicks mostly fire them off just once, but every so often they will double fire that way too.

**Comment by jacobjorvang** [comment]
I’m also hosting on an RPI server. I could try running the Foundry app locally

**Comment by jacobjorvang** [comment]
I haven’t really deep dived into finding the problem source, so I should do that. Clean world, no mods, etc

**Comment by Norc** [comment]
Should be resolved by now using the DF Hotkeys module.
