### ISSUE TITLE
Drag and Drop Doesn't Work with Macro's

### ISSUE THREAD

**Issue by sjkanizaj** [Norc/foundry-custom-hotbar#83]
If I attempt to drag and drop a macro from the "Macro Directory" into the custom hotbar, nothing happens and the console shows the following:

custom-hotbar.js:293 Uncaught (in promise) ReferenceError: coreAssignHotbarMacro is not defined
    at CustomHotbar._onDrop (custom-hotbar.js:293)

I am using version 0.7.7 of Foundry VTT and version 2.0.6 of Custom Hotbar. Thanks for your attention and all your hard work.

**Comment by ghost91-** [comment]
I also ran into this issue. There are 2 aspects as to why this happens: Currently, hotbar drops on the custom hotbar will only work when _something_ is registered for the `'hotbarDrop'` hook. I don't see at all why this is necessary and would simply remove the code reponsible for that. Macro drops worked fine for me once i commented the offending lines that do the check. Secondly in this offending code part, it is attemted to revert some monkey patching that is done before hand if the dropped thing is an Item our RollableTable. However, when a macro is dropped, then the monkey patching never happens and neither does storing the backup to the original function, which is why it's undefined.

@Norc Are you still maintaining this module? Looks like there haven't been any commits in quite a while... If yes, is there any particular reason for the behavior I described above? Otherwise I'll probably create a PR to adjust it. If you are not maintaining it anymore, have you considered handing it over to the League?

**Comment by ghost91-** [comment]
@Norc Ping – Any Update here?

**Comment by Norc** [comment]
Hi folks! Thanks so much for your reports and for using the module.

I'm badly overdue for an update to Custom Hotbar and I'll make sure this gets into it. I expect it to be in the next two weeks. I'm sorry for the delay and that it can't be sooner.

Please feel free to ping me again if you don't hear from me by mid-march, thanks!

**Comment by ghost91-** [comment]
Just as a small hint to solve this particular issue:
In `CustomHotbar._onDrop`, I don't think you should abort if nothing was registered for the `"hotbarDrop"` hook, at least not in the general case. Maybe it's the right thing if an `Item` or `JournalEntry` was dropped but if just a regular macro was dropped, you should just proceed in this case, because dropping macros just works, even if the system doesn't define an special handling for `"hotbarDrop"`.

**Comment by ghost91-** [comment]
@Norc any news?

**Comment by ghost91-** [comment]
@Norc another Ping :)

**Comment by Norc** [comment]
ha, thanks for your help and unwilling patience, I really do appreciate it. 

With 0.8.x rolling closer to reality, the long overdue update will be coming. Soon-ish.

**Comment by Norc** [comment]
Wellp, I have not been able to reproduce this ever. What game system are you folks using?

Regardless, thanks to the info in this ticket I located an issue where my if clauses weren't set up the way they should have been. Logic when dropping something onto CHB should have been:

if (dropping item or rolltable) then (do a monkey hotpatch, and revert it if something unexpected)
Else (if dropping a macro, handle that)

Instead, it was incorrectly:

if (dropping item or rolltable) then (do a monkey hotpatch)
If (something unexpected) then (revert Monkey hotpatch)  //as you pointed out, this could possibly trigger and fail if no item/rolltable provided
If (dropping a macro) then (handle that)


I THINK I'll have this in the latest version, will prop up a dev version for testing. Will close if needs to be reopened.

**Comment by ghost91-** [comment]
@Norc I am using the ds4 system, which I am developing myself. By now, the issue doesn’t appear in my system anymore because I actually added a `hotbarDrop` hook.

In older versions, it’s still possible to reproduce the issue of course. If you want to try to reproduce the issue with that system, just install https://git.f3l.de/dungeonslayers/ds4/-/raw/0.4.1/src/system.json

By the way, thanks a lot for continuing the work on this module. It is greatly appreciated!

**Comment by Norc** [comment]
Perfect!! I was able to reproduce this issue in your old system with the production Custom Hotbar version, but not with my in-development 2.1.0 version. 

Thanks for the excellent feedback and repro help. This fixes an accidental flaw with the Custom Hotbar logic, and it greatly helps with keeping CHB system generic for other in-development systems.
