### ISSUE TITLE
serious issue developed after libwrapper update

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [Norc/foundry-custom-hotbar#87]
having custom hotbar enabled stalls foundry due to new libwrapper update. please fix.

**Comment by LordOHelmet** [comment]
Same here. Game doesn't load properly. 
In the console a number for rendering the CostumHotbar keeps counting.
![customhot_load](https://user-images.githubusercontent.com/80178910/114298187-705f8b80-9ab5-11eb-84e0-c98cd2e4c4a2.JPG)
Thanks for your support!

**Comment by Norc** [comment]
Thanks folks. I'm traveling, but I'll update later today .

Please let the author of libwrapper know also. I don't believe this is a custom hotbar issue really because I do not use lib wrapper as a dependency (that I recall off the top of my head anyway, has been a while)

**Comment by Norc** [comment]
It turns out that this was never an issue with Custom Hotbar but with LibWrapper. Custom Hotbar does not even include LibWrapper.

My understanding is that this was very promptly fixed by the LibWrapper author and there's nothing for me to do here. If this is not true, please reopen this issue and let me know, thanks.
